# Generated by Django 4.2.6 on 2023-10-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_empleados_empleado_rename_productos_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='orden',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
